// app/layout.tsx
import type { Metadata } from "next";
import { SidebarProvider } from "@/components/ui/sidebar";
import Sidebar from "@/components/dashboard/sidebar";
import AppHeader from "@/components/dashboard/header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <SidebarProvider>
      <div className="h-screen w-screen flex flex-row gap-0">
        <aside>
          <Sidebar />
        </aside>
        <div className="w-full min-h-screen">{children}</div>
      </div>
    </SidebarProvider>
  );
}
